/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type AtmAttributeResponseJsonV510 struct {
	Name           string `json:"name"`
	IsActive       bool   `json:"is_active,omitempty"`
	AtmId          string `json:"atm_id"`
	BankId         string `json:"bank_id"`
	Type_          string `json:"type"`
	AtmAttributeId string `json:"atm_attribute_id"`
	Value          string `json:"value"`
}
