/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type TransactionRequestSimple struct {
	OtherAccountSecondaryRoutingAddress string `json:"otherAccountSecondaryRoutingAddress"`
	OtherBankRoutingScheme              string `json:"otherBankRoutingScheme"`
	OtherBranchRoutingScheme            string `json:"otherBranchRoutingScheme"`
	OtherAccountRoutingScheme           string `json:"otherAccountRoutingScheme"`
	OtherBankRoutingAddress             string `json:"otherBankRoutingAddress"`
	OtherAccountRoutingAddress          string `json:"otherAccountRoutingAddress"`
	OtherAccountSecondaryRoutingScheme  string `json:"otherAccountSecondaryRoutingScheme"`
	OtherBranchRoutingAddress           string `json:"otherBranchRoutingAddress"`
}
