/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type CounterpartyJson400 struct {
	OtherAccountRoutingAddress          string                        `json:"other_account_routing_address"`
	OtherAccountRoutingScheme           string                        `json:"other_account_routing_scheme"`
	CreatedByUserId                     string                        `json:"created_by_user_id"`
	Name                                string                        `json:"name"`
	OtherAccountSecondaryRoutingAddress string                        `json:"other_account_secondary_routing_address"`
	IsBeneficiary                       bool                          `json:"is_beneficiary"`
	Description                         string                        `json:"description"`
	OtherBranchRoutingAddress           string                        `json:"other_branch_routing_address"`
	Bespoke                             []PostCounterpartyBespokeJson `json:"bespoke"`
	OtherBankRoutingScheme              string                        `json:"other_bank_routing_scheme"`
	OtherBranchRoutingScheme            string                        `json:"other_branch_routing_scheme"`
	ThisAccountId                       string                        `json:"this_account_id"`
	ThisViewId                          string                        `json:"this_view_id"`
	Currency                            string                        `json:"currency"`
	OtherBankRoutingAddress             string                        `json:"other_bank_routing_address"`
	ThisBankId                          string                        `json:"this_bank_id"`
	CounterpartyId                      string                        `json:"counterparty_id"`
	OtherAccountSecondaryRoutingScheme  string                        `json:"other_account_secondary_routing_scheme"`
}
