/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type JsonDynamicResourceDocSuccessResponseBody struct {
	MyUserId        string   `json:"my_user_id"`
	Name            string   `json:"name"`
	Age             int32    `json:"age"`
	Hobby           []string `json:"hobby"`
	OptionalFields_ []string `json:"_optional_fields_"`
}
