/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type EntitlementRequestJson struct {
	EntitlementRequestId string        `json:"entitlement_request_id"`
	RoleName             string        `json:"role_name"`
	BankId               string        `json:"bank_id"`
	User                 *UserJsonV200 `json:"user"`
	Created              string        `json:"created"`
}
