/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type TransactionRequestBodyAllTypes struct {
	ToTransferToPhone     *TransactionRequestTransferToPhone   `json:"to_transfer_to_phone,omitempty"`
	Description           string                               `json:"description"`
	ToTransferToAtm       *TransactionRequestTransferToAtm     `json:"to_transfer_to_atm,omitempty"`
	ToCounterparty        *TransactionRequestCounterpartyId    `json:"to_counterparty,omitempty"`
	ToSepaCreditTransfers *SepaCreditTransfers                 `json:"to_sepa_credit_transfers,omitempty"`
	ToSimple              *TransactionRequestSimple            `json:"to_simple,omitempty"`
	ToSepa                *TransactionRequestIban              `json:"to_sepa,omitempty"`
	ToTransferToAccount   *TransactionRequestTransferToAccount `json:"to_transfer_to_account,omitempty"`
	Value                 *AmountOfMoney                       `json:"value"`
	ToSandboxTan          *TransactionRequestAccount           `json:"to_sandbox_tan,omitempty"`
}
