/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type UpdateViewJsonV300 struct {
	Description             string   `json:"description"`
	IsPublic                bool     `json:"is_public"`
	HideMetadataIfAliasUsed bool     `json:"hide_metadata_if_alias_used"`
	WhichAliasToUse         string   `json:"which_alias_to_use"`
	IsFirehose              bool     `json:"is_firehose,omitempty"`
	MetadataView            string   `json:"metadata_view"`
	AllowedActions          []string `json:"allowed_actions"`
}
