/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type ProductFeeResponseJsonV400 struct {
	Name         string                   `json:"name"`
	IsActive     bool                     `json:"is_active"`
	ProductCode  string                   `json:"product_code"`
	MoreInfo     string                   `json:"more_info"`
	BankId       string                   `json:"bank_id"`
	ProductFeeId string                   `json:"product_fee_id"`
	Value        *ProductFeeValueJsonV400 `json:"value"`
}
