/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type InlineResponse200ScannedApiVersions struct {
	UrlPrefix       string `json:"urlPrefix"`
	ApiStandard     string `json:"apiStandard"`
	ApiShortVersion string `json:"apiShortVersion"`
	API_VERSION     string `json:"API_VERSION"`
}
