/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type SandboxAccountImport struct {
	GenerateAuditorsView    bool                  `json:"generate_auditors_view"`
	Number                  string                `json:"number"`
	IBAN                    string                `json:"IBAN"`
	Label                   string                `json:"label"`
	Owners                  []string              `json:"owners"`
	Balance                 *SandboxBalanceImport `json:"balance"`
	Bank                    string                `json:"bank"`
	Id                      string                `json:"id"`
	Type_                   string                `json:"type"`
	GenerateAccountantsView bool                  `json:"generate_accountants_view"`
	GeneratePublicView      bool                  `json:"generate_public_view"`
}
