/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type ConsentInfoJsonV400 struct {
	CreatedByUserId string `json:"created_by_user_id"`
	ApiVersion      string `json:"api_version"`
	LastUsageDate   string `json:"last_usage_date"`
	Status          string `json:"status"`
	ConsumerId      string `json:"consumer_id"`
	ApiStandard     string `json:"api_standard"`
	ConsentId       string `json:"consent_id"`
	LastActionDate  string `json:"last_action_date"`
}
