/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type UserAuthContextJsonV500 struct {
	TimeStamp         string `json:"time_stamp"`
	UserId            string `json:"user_id"`
	Key               string `json:"key"`
	ConsumerId        string `json:"consumer_id"`
	UserAuthContextId string `json:"user_auth_context_id"`
	Value             string `json:"value"`
}
