/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type ConsentRequestResponseJsonPayload struct {
	Everything    bool                                             `json:"everything"`
	AccountAccess []ConsentRequestResponseJsonPayloadAccountAccess `json:"account_access"`
	PhoneNumber   string                                           `json:"phone_number"`
	ValidFrom     string                                           `json:"valid_from"`
	TimeToLive    int32                                            `json:"time_to_live"`
}
