/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type MessageDocJson struct {
	AdapterImplementation  *AdapterImplementationJson        `json:"adapter_implementation"`
	OutboundAvroSchema     *MessageDocJsonOutboundAvroSchema `json:"outboundAvroSchema,omitempty"`
	ExampleInboundMessage  *MessageDocJsonOutboundAvroSchema `json:"example_inbound_message"`
	InboundAvroSchema      *MessageDocJsonOutboundAvroSchema `json:"inboundAvroSchema,omitempty"`
	RequiredFieldInfo      *FieldNameApiVersions             `json:"requiredFieldInfo,omitempty"`
	Description            string                            `json:"description"`
	Process                string                            `json:"process"`
	MessageFormat          string                            `json:"message_format"`
	ExampleOutboundMessage *MessageDocJsonOutboundAvroSchema `json:"example_outbound_message"`
	DependentEndpoints     []EndpointInfo                    `json:"dependent_endpoints"`
	OutboundTopic          string                            `json:"outbound_topic,omitempty"`
	InboundTopic           string                            `json:"inbound_topic,omitempty"`
}
