/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type UpdateAccountResponseJsonV310 struct {
	BranchId        string                   `json:"branch_id"`
	AccountRoutings []AccountRoutingJsonV121 `json:"account_routings"`
	Label           string                   `json:"label"`
	BankId          string                   `json:"bank_id"`
	AccountId       string                   `json:"account_id"`
	Type_           string                   `json:"type"`
}
