/*
 * Open Bank Project API
 *
 * An Open Source API for Banks. (c) TESOBE GmbH. 2011 - 2024. Licensed under the AGPL and commercial licences.
 *
 * API version: v5.1.0
 * Contact: contact@tesobe.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package obp_golang

type OrderObjectJson struct {
	OrderId             string `json:"order_id"`
	NumberOfCheckbooks  string `json:"number_of_checkbooks"`
	FirstCheckNumber    string `json:"first_check_number"`
	OrderDate           string `json:"order_date"`
	Status              string `json:"status"`
	ShippingCode        string `json:"shipping_code"`
	DistributionChannel string `json:"distribution_channel"`
}
